// iruka - ReXGlue Recompiled Project
// Generated by: rexglue migrate
//
// This file is SDK-managed. Customizations go in virtual hook overrides.
// Running 'rexglue migrate' will overwrite this file.

#include "generated/iruka_config.h"
#include "generated/iruka_init.h"

#include <rex/rex_app.h>

class IrukaApp : public rex::ReXApp {
 public:
  using rex::ReXApp::ReXApp;

  static std::unique_ptr<rex::ui::WindowedApp> Create(
      rex::ui::WindowedAppContext& ctx) {
    return std::unique_ptr<IrukaApp>(new IrukaApp(ctx, "iruka",
        {PPC_CODE_BASE, PPC_CODE_SIZE, PPC_IMAGE_BASE,
         PPC_IMAGE_SIZE, PPCFuncMappings}));
  }
};

REX_DEFINE_APP(iruka, IrukaApp::Create)
